sudo: false
addons:
  apt:
    packages:
    - libgmp-dev    # this is needed for ruby-2.1.10 and ruby-head on linux
language: ruby
before_install:
  - gem install bundler
script: bundle exec rake test
os:
  - linux
  - osx
rvm:
  - "2.0.0"
  - "2.1"
  - "2.2"
  - "2.3.3"
  - "ruby-head"
  - "ruby-head-clang"
  - "rbx"
  - "system"
env:
  - CC=gcc
  - CC=clang
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: mruby
    - rvm: system
    - rvm: "rbx"
    - rvm: "rbx-head"
    - rvm: "ruby-head-clang"
after_failure:
  - "find build -name mkmf.log | xargs cat"
